### ISSUE TITLE
get time + distance + indication to next leg

### ISSUE THREAD

**Issue by TheBigR** [Webiks/Phraze#19]
- [x] divide route legs into elements and put them into store

- [x] add effect to send current location with leg params to turf calculation functions

- [x] send calculations into store

**Comment by TheBigR** [comment]
estimate - 10h

**Comment by TheBigR** [comment]
turf calculation functions were added to navigation service and pull params directly from the store.
