### ISSUE TITLE
Set map and camera initial params

### ISSUE THREAD

**Issue by TheBigR** [Webiks/Phraze#2]
User story: #1 

Tasks:
- [x] point map towards north.
- [x] set camera position at a given altitude.
- [x] set camera angle at a given position.

**Comment by TheBigR** [comment]
must

**Comment by TheBigR** [comment]
#estimate: 6h
