### ISSUE TITLE
code review and refactoring

### ISSUE THREAD

**Issue by TheBigR** [Webiks/Phraze#23]
- [x] releasing 3rd sprint ver.

- [x] perform full code review.

- [x] refactor code according to remarks.

- [x] upload version 

estimate - 8h
