### ISSUE TITLE
Map provider change

### ISSUE THREAD

**Issue by TheBigR** [Webiks/Phraze#24]
- [ ] ~~move map provider options to config.json~~

- [x] add provider options with bing maps

- [x] add provider options with mapbox

#estimate 4h

**Comment by TheBigR** [comment]
#estimate: 2h
