### ISSUE TITLE
Hear navigation commands

### ISSUE THREAD

**Issue by TheBigR** [Webiks/Phraze#8]
#7 

- [x] hear that navigation began.

- [x] hear the next direction.

- [x] hear when arrived to destination.

**Comment by TheBigR** [comment]
#estimate 8h
